@startuml
title AgroTech Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(rancher, "Сотрудник фермы", "Получает данные из системы и передает данные с фермы")
Person(operator, "Оператор", "Администратор управляющий системой ")
System(CameraSystem, "Система управления камерами", "Система обработки данных с камер")
System(AgroTechSystem, "Система AgroTech", "Система обработки данных с фермы")

Rel(rancher, AgroTechSystem, "Передача данных в систему")
Rel(CameraSystem, AgroTechSystem, "Передача данных в систему")
Rel(operator,AgroTechSystem,"Управление системой")


@enduml