@startuml
title AgroTech Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(operator, "Оператор", "Администратор управляющий системой ")
System(AgroTechSystem, "Система AgroTech", "Система обработки данных с фермы")
System(Agent, "Агент", "Агент фермы")

Container_Boundary(AgroTechSystem, "Система AgroTech") {
  Container(WebApp, "Web Application", "Java, Spring", "Позволяет оператору управлять данными с фермы")
  Container(Database, "Database", "PostgreSQL", "Хранит данные о состоянии фермы")
  Container(CameraSystem, "Система управления камерами", "AI Agent", "Обработка данных с камер")
  Container(DrinkingSystem, "Система управления поилками", "Java, Spring", "Обработка данных с поилок")
  Container(CentralServer, "Центральный сервер", "Java, Spring", "Обработка данных с фермы")
  Container(FeedingSystem, "Система управления кормушками", "Java, Spring", "Обработка данных с кормушек")

}

Rel(CameraSystem, CentralServer, "Запись данных в систему")
Rel(operator,WebApp,"Управление системой")
Rel(WebApp, CentralServer, "Чтение/запись данных фермы")
Rel(DrinkingSystem, CentralServer, "Запись данных в систему")
Rel(CentralServer, Database, "Запись и чтение из базы")
Rel(FeedingSystem, CentralServer, "Запись данных в систему")


@enduml