@startuml
title AgroTech Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(rancher, "Сотрудник фермы компании A", "Получает данные из системы и передает данные с фермы")
Person(operator, "Оператор компании A", "Администратор управляющий системой ")
System(AgroTechSystem, "Система AgroTech", "Система обработки данных с фермы")

System_Ext(bank, "Bank System", "Удаленный банк для обработки платежей")

Rel(rancher, AgroTechSystem, "Передача данных в систему")
Rel(operator,AgroTechSystem,"Управление системой")
Rel(AgroTechSystem,bank,"Обработка платежей")


@enduml